import 'package:flutter/widgets.dart';

import '../modifier.dart';


/// An inherited widget used to indicate which autocomplete option should be
/// highlighted for keyboard navigation.
///
/// The `RawAutoComplete` widget will wrap the options view generated by the
/// `optionsViewBuilder` with this widget to provide the highlighted option's
/// index to the builder.
///
/// In the builder callback the index of the highlighted option can be obtained
/// by using the static [of] method:
///
/// ```dart
/// final highlightedIndex = AutocompleteHighlightedOption.of(context);
/// ```
///
/// which can then be used to tell which option should be given a visual
/// indication that will be the option selected with the keyboard.
class AutocompleteHighlightedOptionModifier extends SingleChildStatelessModifier {
  /// Create an instance of AutocompleteHighlightedOption inherited widget.
  const AutocompleteHighlightedOptionModifier({
    super.key,
    required this.highlightIndexNotifier,
    required super.child,
  });

  /// No docs
  final ValueNotifier<int> highlightIndexNotifier;

  @override
  Widget buildWithChild(BuildContext context, Widget? child) {
    return AutocompleteHighlightedOption(
      key: modifierKey,
      highlightIndexNotifier: highlightIndexNotifier,
      child: child!,
    );
  }
}
